2025-04-01 23:56:10.624 [info] 




2025-04-01 23:56:10.689 [info] Extension host agent started.
2025-04-01 23:56:11.070 [info] [<unknown>][d1809b9c][ManagementConnection] New connection established.
2025-04-01 23:56:11.073 [info] [<unknown>][8b43a092][ExtensionHostConnection] New connection established.
2025-04-01 23:56:11.247 [info] [<unknown>][8b43a092][ExtensionHostConnection] <647> Launched Extension Host Process.
2025-04-01 23:56:23.162 [error] CodeExpectedError: Could not find pty 4 on pty host
    at I.W (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:45:12275)
    at I.updateTitle (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:45:7722)
    at O.s.<computed> (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:45:2962)
    at Object.call (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:28:4204)
    at el.s (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:26:80918)
    at el.q (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:26:80441)
    at ds.value (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:26:79843)
    at x.B (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:26:2373)
    at x.fire (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:26:2591)
    at process.C (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:24:29877)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:950:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2025-04-01 23:56:23.171 [error] CodeExpectedError: Could not find pty 4 on pty host
    at I.W (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:45:12275)
    at I.updateIcon (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:45:7772)
    at O.s.<computed> (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:45:2962)
    at Object.call (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:28:4204)
    at el.s (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:26:80918)
    at el.q (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:26:80441)
    at ds.value (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:26:79843)
    at x.B (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:26:2373)
    at x.fire (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:26:2591)
    at process.C (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/vs/platform/terminal/node/ptyHostMain.js:24:29877)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:950:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2025-04-02 00:01:10.709 [info] New EH opened, aborting shutdown
2025-04-03 05:20:46.113 [info] [<unknown>][d1809b9c][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
2025-04-03 08:20:29.991 [info] [<unknown>][8b43a092][ExtensionHostConnection] <647> Extension Host Process exited with code: 0, signal: null.
2025-04-03 08:20:30.020 [info] Last EH closed, waiting before shutting down
2025-04-03 08:20:30.042 [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (file:///home/aituter/.vscode-server/cli/servers/Stable-ddc367ed5c8936efe395cffeec279b04ffd7db78/server/out/server-main.js:183:1060)
    at process.emit (node:events:530:35)
2025-04-03 08:20:55.560 [info] [<unknown>][d1809b9c][ManagementConnection] The reconnection grace time of 3h has expired, so the connection will be disposed.
2025-04-03 08:25:30.029 [info] Last EH closed, shutting down
